channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-bambu>=3.4.0
  - r-biocmanager
  - r-xgboost<=1.7.6
  - espresso>=1.3.2
  - isoquant>=3.3.1
  - perl>=5.22.0.1
  - porechop_abi>=0.5.0
  - rnabloom>=2.0.1
  - stringtie>=2.2.1
  - seqkit>=2.4.0
  - gffcompare>=0.12.6
  - gffread>=0.12.7
  - gmap>=2023.07.20
  - samtools>=1.17
  - polars>=0.19.18
  - pysam>=0.22.0
